resource_group_name = "<resource_group_name>"
location = "<azure_location>"
adminUsername = "paloalto"
adminPassword = "<password>"
allowed_src_ip = "0.0.0.0/0"
twistlock_download_url = "<twistlock_download_url>"
license_key = "<license_key>"
vmSize = "Standard_D2s_v3"